In [3]:
import spacy
import pandas as pd

In [4]:
nlp = spacy.load('en_core_web_sm')

In [5]:
emma = 'Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of\
the best blessings of existence, and had lived nearly twenty-one years in the world with very little to distress or vex her.\
She was the youngest of the two daughters of a most affectionate, indulgent father, and had, in consequence of her sister’s \
Marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an \
indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little \
short of a mother in affection.'

In [6]:
emma

'Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some ofthe best blessings of existence, and had lived nearly twenty-one years in the world with very little to distress or vex her.She was the youngest of the two daughters of a most affectionate, indulgent father, and had, in consequence of her sister’s Marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection.'

In [7]:
spacy_doc = nlp(emma)

In [8]:
spacy_doc

Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some ofthe best blessings of existence, and had lived nearly twenty-one years in the world with very little to distress or vex her.She was the youngest of the two daughters of a most affectionate, indulgent father, and had, in consequence of her sister’s Marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection.

In [9]:
pos_df = pd.DataFrame(columns = ['token', 'pos'])
pos_df

Empty DataFrame
Columns: [token, pos]
Index: []

In [12]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, 'pos': token.pos_}])], ignore_index=True)
pos_df

         token    pos
0         Emma  PROPN
1    Woodhouse  PROPN
2            ,  PUNCT
3     handsome    ADJ
4            ,  PUNCT
..         ...    ...
385          a    DET
386     mother   NOUN
387         in    ADP
388  affection   NOUN
389          .  PUNCT

[390 rows x 2 columns]

In [22]:
pos_df.groupby(['token', 'pos']).size().sort(by='counts')

token     pos
,         PUNCT    33
-         PUNCT     3
.         PUNCT     9
;         PUNCT     3
Emma      PROPN     3
                   ..
woman     NOUN      3
world     NOUN      3
years     NOUN      3
youngest  ADJ       3
’s        PART      3
Length: 86, dtype: int64

In [21]:
pos_df.groupby('pos').count()

       token
pos
ADJ       48
ADP       48
ADV       21
AUX       21
CCONJ     18
DET       30
NOUN      69
NUM        9
PART      12
PRON      30
PROPN      6
PUNCT     48
SCONJ      3
VERB      27